version: '3.8'
#name: cadastral.app.container.docker
services:
  data:
    container_name: tesis.data.container.docker
    image: postgres:latest
    volumes: 
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5433
    environment:
      - POSTGRES_DB=tesis
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
  backend:
    container_name: tesis.flask.container.docker
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Backend:/usr/src/Backend
    ports:
      - 5001:5001
    environment:
      - DB_SERVER:data
      - POSTGRES_DB=tesis
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    links:
      - data
    networks:
      - tesis_network

  frontend:
    container_name: tesis.react.container.docker
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Frontend:/usr/src/Frontend
    ports:
      - 80:81
    links:
      - backend
    networks:
      - tesis_network

volumes:
  data:

#[optional] If the network is not created, docker will create by itself.
networks:
  tesis_network: {}

