FLASK_APP="wsgi.py"
FLASK_RUN_HOST= "0.0.0.0"
FLASK_RUN_PORT=5001
FLASK_ENV="dev"
SECRET_KEY= "secret"
VERSION=1
API_URL="/api/v1/"
TITLE="API DEV"
CORS="*"
CORS_ORIGIN="*"
TEMPORARY_PATH="tmp"
DATABASE_URL_DEV="sqlite:///db.sqlite"
DATABASE_URL_TEST="sqlite:///db.sqlite"
DATABASE_URL="sqlite:///db.sqlite"
HOST=24